from dataclasses import dataclass
from typing import Union


@dataclass(frozen = True, slots = True)
class DriveFile:
    """
    Represents a Google Drive file.
    """

    id: str
    name: str
    mime_type: str
    size: Union[int, None]
    web_view_link: Union[str, None] = None
    web_content_link: Union[str, None] = None

    @property
    def shareable_link(
        self
    ) -> str:
        """
        A link to share the resource in Google
        Drive, generated by sharing the resource.

        This link will be available only if the
        resource has been shared previously.

        This is not a direct link to download it,
        check `.direct_file_link` instead.
        """
        return f'https://drive.google.com/file/d/{self.id}/view?usp=drive_link'

    @property
    def direct_file_link(
        self,
    ) -> str:
        """
        A direct link to the file that allows you
        to download it from this link.
        """
        return f'https://drive.google.com/uc?export=download&id={self.id}'